---
- name: Reset host entry
  ansible.builtin.set_fact:
    hostentry: ""
- name: Reset host entry
  ansible.builtin.set_fact:
    hostentry_combined: ""
- name: Combine host entry
  ansible.builtin.include_tasks: 10-etc_hosts_entry_name.yml
  loop: "{{ hostvars[inventory_hostname][configgroup]['config']['hosts'][ip] }}"
  loop_control:
    loop_var: name
- name: "Add to /etc/hosts {{ ip }}"
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    state: present
    regexp: "{{ ip }}[ \t]+{{ hostentry }}"
    line: "{{ ip }}  {{ hostentry }}"
  become: "{{ lihas_become }}"
...
