---
- name: "/etc/hosts: {{ configspace }}"
  include_tasks: 10-etc_hosts_entry.yml
  loop: "{{ hostvars[inventory_hostname][configgroup]['config'].hosts | default({}) | flatten(levels=1) }}"
  loop_control:
    loop_var: ip
...
