---
- name: "DEBUG: file"
  ansible.builtin.debug:
    var: file
  tags:
    - templatesperms
- name: Copy additional files/templates with permissions
  ansible.builtin.template:
    src: "{{ file }}"
    dest: "/{{ file }}"
    mode: "{{ lihas_common_extra_files_with_perms[filegroupid]['perm']['mode'] | default(664) }}"
    owner: "{{ lihas_common_extra_files_with_perms[filegroupid]['perm']['owner'] | default('root') }}"
    group: "{{ lihas_common_extra_files_with_perms[filegroupid]['perm']['group'] | default('root') }}"
    unsafe_writes: "{{ lihas_common_extra_files_with_perms[filegroupid]['unsafe'] | default(false) }}"
  register: resulttemplateperms
  tags:
    - templatesperms
  become: "{{ lihas_become }}"
- name: "DEBUG: resulttemplateperms"
  ansible.builtin.debug:
    var: resulttemplateperms
  tags:
    - templatesperms
- name: Run templatesperms, notifies
  ansible.builtin.shell:
    cmd: "{{ lihas_common_extra_files_with_perms[filegroupid]['command'] }}"
  with_list: '{{ resulttemplateperms.results }}'
  when: resulttemplateperms.changed and lihas_common_extra_files_with_perms[filegroupid]['command'] is defined
  tags:
    - templatesperms
  become: "{{ lihas_become }}"
...
