---
- name: "DEBUG: file"
  ansible.builtin.debug:
    var: file
    verbosity: 1
  tags:
    - templatesperms
- name: Copy additional files/templates with permissions
  ansible.builtin.copy:
    src: "{{ file }}"
    dest: "/{{ file }}"
    mode: "{{ lihas_common_extra_filesbinary[filegroupid]['perm']['mode'] | default(664) }}"
    owner: "{{ lihas_common_extra_filesbinary[filegroupid]['perm']['owner'] | default('root') }}"
    group: "{{ lihas_common_extra_filesbinary[filegroupid]['perm']['group'] | default('root') }}"
  register: resulttemplateperms
  tags:
    - templatesperms
  become: "{{ lihas_become }}"
- name: "DEBUG: resulttemplateperms"
  ansible.builtin.debug: # noqa: no-handler
    var: resulttemplateperms
  tags:
    - templatesperms
  when: resulttemplateperms.changed
- name: Run templatesperms, notifies
  ansible.builtin.shell: # noqa: command-instead-of-shell
    cmd: "{{ lihas_common_extra_filesbinary[filegroupid]['command'] }}"
  with_list: '{{ resulttemplateperms.results }}'
  changed_when: false
  when: lihas_common_extra_filesbinary[filegroupid]['command'] is defined and resulttemplateperms.changed
  tags:
    - templatesperms
  become: "{{ lihas_become }}"
...
