---
- name: "debug: file" 
  debug: 
    var: file 
  tags: 
    - templatesperms 
- name: copy additional files/templates with permissions
  template:
    src: "{{ file.key }}"
    dest: "/{{ file.key }}"
    mode: "{{ lihas_common_extra_files_with_perms[filegroupid]['perm']['mode'] | default(664) }}"
    owner: "{{ lihas_common_extra_files_with_perms[filegroupid]['perm']['owner'] | default('root') }}"
    group: "{{ lihas_common_extra_files_with_perms[filegroupid]['perm']['group'] | default('root') }}"
  register: resulttemplateperms
  tags:
    - templatesperms
  become: yes
- name: Debug resulttemplateperms
  debug:
    var: resulttemplateperms
  tags:
    - templatesperms
  when: resulttemplateperms.changed
- name: templatesperms, notifies
  shell:
    cmd: "{{ lihas_common_extra_files_with_perms[filegroupid]['command'] }}"
  with_list: resulttemplateperms.results
  when: resulttemplateperms.changed and lihas_common_extra_files_with_perms[filegroupid]['command'] is defined
  tags:
    - templatesperms
  become: yes
...
