- name: Create/modify user
  ansible.builtin.user:
    name: "{{ user }}"
    uid: "{{ lihas_common_users[user].uid | default(omit) }}"
    group: "{{ lihas_common_users[user].group | default(omit) }}"
    shell: "{{ lihas_common_users[user].shell | default(omit) }}"
    comment: "{{ lihas_common_users[user].comment | default(omit) }}"
    home: "{{ lihas_common_users[user].home | default(omit) }}"
    create_home: "{{ lihas_common_users[user].create_home | default(true) }}"
    groups: "{{ lihas_common_users[user].groups | default(omit) }}"
    state: "{{ lihas_common_users[user].state | default('present') }}"
  tags:
    - users
  become: "{{ lihas_become }}"
- name: "Home directory permissions in case we had previous content there"
  ansible.builtin.file:
    path: "{{ lihas_common_users[user].home | default('/home/' + user) }}"
    state: directory
    owner: "{{ user }}"
    recurse: true
  when: lihas_common_users[user].force_home_user | default(false)
  tags:
    - users
  become: "{{ lihas_become }}"
- name: "Add ssh key"
  ansible.posix.authorized_key:
    key: "{{ sshkey }}"
    manage_dir: true
    user: "{{ user }}"
    path: "{{ lihas_common_users[user].home | default('/home/' + user) + '/.ssh/authorized_keys' }}"
  loop: "{{ lihas_common_users[user].ssh_authorized_keys | default([]) }}"
  loop_control:
    loop_var: sshkey
  tags:
    - users
  become: "{{ lihas_become }}"
- name: "Add sudo"
  ansible.builtin.template:
    dest: "/etc/sudoers.d/{{ user }}"
    mode: "0440"
    owner: root
    group: root
    validate: 'visudo -cf %s'
    src: "etc/sudoers.d/sudo.j2"
  tags:
    - users
  become: "{{ lihas_become }}"
  when: lihas_common_users[user].sudo | default(false)
...
