---
- name: Find additional files/templates with permissions
  ansible.builtin.set_fact:
    lihas_common_extra_files_with_perms: >-
      {{ lihas_common_extra_files_with_perms | default([]) +
      hostvars[inventory_hostname][item]['config']['fileswithpermissions'] | default([]) }}
  loop: "{{ configspaces }}"
  when: hostvars[inventory_hostname][item]['config']['fileswithpermissions'] is defined
  tags:
    - templatesperms
- name: Debug Create directories with permissions
  ansible.builtin.debug:
    var: lihas_common_extra_files_with_perms | default([])
    verbosity: 1
  tags:
    - templatesperms
- name: "Files: include tasks/10-files.yml"
  ansible.builtin.include_tasks: tasks/10-files.yml
  loop: "{{ lihas_common_extra_files_with_perms | default([]) }}"
  loop_control:
    loop_var: filegroup
    index_var: filegroupid
  tags:
    - templatesperms
...
