---
- name: Reconfigure locales
  ansible.builtin.shell: LANG=C dpkg-reconfigure -f noninteractive locales
- name: Reconfigure tzdata
  ansible.builtin.shell: LANG=C dpkg-reconfigure -f noninteractive tzdata
- name: Restart routing-lihas
  ansible.builtin.service:
    name: routing-lihas
    state: restarted
  tags:
    - routes
...
