---
- name: reconfigure locales
  ansible.builtin.command: dpkg-reconfigure -f noninteractive locales
- name: reconfigure tzdata
  ansible.builtin.command: dpkg-reconfigure -f noninteractive tzdata
- name: restart_routing-lihas
  ansible.builtin.service:
    name: routing-lihas
    state: restarted
  tags:
    - routes
...
